### ISSUE TITLE
Problem with floc example

### ISSUE THREAD

**Issue by rsignell-usgs** [tjcrone/camhdhub#2]
Tried to run floc example here: 
https://github.com/tjcrone/cce/blob/master/examples/floc.ipynb
using jupyterhub here: 
https://chiron.ldeo.columbia.edu/jupyter
and got back: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-03961a455bdf> in <module>()
      1 import matplotlib.patches as patches
      2 plt.rc('figure', figsize=(11, 11))
----> 3 frame = camhd.get_frame(filenames[2], frame_numbers[0], 'gray16le')
      4 fig, ax = plt.subplots();
      5 im1 = ax.imshow(frame);

AttributeError: module 'pycamhd' has no attribute 'get_frame'
```
I guess either 
* the notebook is out of date
* I need to upgrade pycamhd in the jupyterhub environment 

I didn't seem to be able to run the notebook in my own environment on that jupyterhub -- the custom kernel I created does not show up.  

I'm guessing the root environment on that jupyterhub needs to have `nb_conda_kernels` installed:
```
conda install -c conda-forge nb_conda_kernels
```

**Comment by tjcrone** [comment]
Import pycamhd like this:

`import pycamhd.pycamhd as camhd`

I have fixed the example. Thanks for finding this.
